import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import type { Express } from 'express';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface ElementSourceDef {
  id: string;
  title: string;
  attribution: string;
  attributionUrl: string;
  license: string;
}

const ARROW_SOURCES: ElementSourceDef[] = [
  {
    id: 'handyarrows',
    title: 'Handy Arrows',
    attribution: 'Eren Cana Arica',
    attributionUrl: 'https://handyarrows.com',
    license: 'CC-BY 4.0',
  },
  {
    id: 'yokui',
    title: 'Yokui',
    attribution: 'Yokui (Figma Community)',
    attributionUrl: 'https://www.figma.com/design/drOVURBi5jiqueM88edcTK/Yokui---Hand-Drawn-Arrows--Community-',
    license: 'Figma Community — Free for Use',
  },
  {
    id: 'handdrowing',
    title: 'Hand-Drawing',
    attribution: 'arrows hand-drowing (Figma Community)',
    attributionUrl: 'https://www.figma.com/design/sLdWVs5Z7gMQGiGEO4lYqM/arrows-hand-drowing--Community-',
    license: 'Figma Community — Free for Use',
  },
];

const BLOB_SOURCES: ElementSourceDef[] = [
  {
    id: 'figma-blobs',
    title: 'Blobs (Figma Community)',
    attribution: 'Blobs and Section Waves (Figma Community)',
    attributionUrl: 'https://www.figma.com/design/0xRmMhQRUuzfDEL25mkhad/Blobs-and-Section-Waves--Community-',
    license: 'Figma Community — Free for Use',
  },
];

export function registerElementsRoutes(app: Express): void {
  // ---------- Elements: Icons (Lucide) ----------
  // Catalog is built once on first request from lucide-static's tags.json.
  // Each SVG is read from disk on demand; the client recolors them locally.
  let iconCatalogCache: { name: string; tags: string[] }[] | null = null;
  let iconCatalogError: string | null = null;
  const requireFromHere = createRequire(import.meta.url);
  const lucideTagsPath = (() => {
    try {
      return requireFromHere.resolve('lucide-static/tags.json');
    } catch {
      return null;
    }
  })();
  const lucideIconsDir = lucideTagsPath ? join(dirname(lucideTagsPath), 'icons') : null;

  async function loadIconCatalog(): Promise<{ name: string; tags: string[] }[]> {
    if (iconCatalogCache) return iconCatalogCache;
    if (!lucideTagsPath) {
      iconCatalogError = 'lucide-static not installed';
      return [];
    }
    const raw = await readFile(lucideTagsPath, 'utf-8');
    const parsed = JSON.parse(raw) as Record<string, string[]>;
    iconCatalogCache = Object.entries(parsed).map(([name, tags]) => ({ name, tags }));
    return iconCatalogCache;
  }

  app.get('/api/elements/icons/catalog', async (_req, res) => {
    try {
      const catalog = await loadIconCatalog();
      res.json({ source: 'lucide', icons: catalog });
    } catch (err) {
      const message = err instanceof Error ? err.message : iconCatalogError || 'Unknown error';
      res.status(500).json({ error: message });
    }
  });

  // Category metadata snapshot generated by scripts/sync-lucide-categories.mjs.
  // Lives under packages/web-preview/data/ so it's reachable both from
  // dist/ (one level up) and via the package's "files" allowlist.
  const lucideCategoriesPath = join(__dirname, '..', '..', 'data', 'lucide-categories.json');
  let lucideCategoriesCache: {
    categories: { id: string; title: string }[];
    iconCategories: Record<string, string[]>;
  } | null = null;

  app.get('/api/elements/icons/categories', async (_req, res) => {
    try {
      if (!lucideCategoriesCache) {
        const raw = await readFile(lucideCategoriesPath, 'utf-8');
        lucideCategoriesCache = JSON.parse(raw);
      }
      res.json(lucideCategoriesCache);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to load categories';
      res.status(500).json({ error: message });
    }
  });

  // ---------- Elements: Arrows ----------
  // Sources live under packages/web-preview/data/arrows/<source>/. Each
  // source bundles a set of hand-curated arrow SVGs from a specific
  // creator/pack — see the per-source attribution surfaced in the picker.
  const arrowsBaseDir = join(__dirname, '..', '..', 'data', 'arrows');

  app.get('/api/elements/arrows/catalog', async (_req, res) => {
    try {
      const { readdir, stat } = await import('node:fs/promises');
      const sources = await Promise.all(
        ARROW_SOURCES.map(async (source) => {
          const dir = join(arrowsBaseDir, source.id);
          let files: string[] = [];
          try {
            files = (await readdir(dir)).filter((n) => n.endsWith('.svg'));
          } catch {
            // Source folder absent — return empty list rather than 500.
          }
          files.sort((a, b) => {
            const an = parseInt(a.match(/(\d+)/)?.[1] ?? '0', 10);
            const bn = parseInt(b.match(/(\d+)/)?.[1] ?? '0', 10);
            return an - bn;
          });
          // Stamp each arrow with the file's mtime in seconds — the client
          // appends it to the SVG fetch URL as a version hint so updates
          // bust any client-side cache. Falling back to 0 keeps the URL
          // stable if stat fails.
          const arrows = await Promise.all(
            files.map(async (f) => {
              const name = f.replace(/\.svg$/, '');
              let v = 0;
              try {
                v = Math.floor((await stat(join(dir, f))).mtimeMs / 1000);
              } catch {
                // ignore — use 0
              }
              return { name, v };
            }),
          );
          return { ...source, arrows };
        }),
      );
      res.json({ sources });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to load arrows catalog';
      res.status(500).json({ error: message });
    }
  });

  // ---------- Elements: Blobs ----------
  // Same shape as the arrows pipeline: SVGs under data/blobs/<source>/,
  // each with its own attribution/license metadata.
  const blobsBaseDir = join(__dirname, '..', '..', 'data', 'blobs');

  app.get('/api/elements/blobs/catalog', async (_req, res) => {
    try {
      const { readdir, stat } = await import('node:fs/promises');
      const sources = await Promise.all(
        BLOB_SOURCES.map(async (source) => {
          const dir = join(blobsBaseDir, source.id);
          let files: string[] = [];
          try {
            files = (await readdir(dir)).filter((n) => n.endsWith('.svg'));
          } catch {
            // Source folder absent — return empty list rather than 500.
          }
          files.sort((a, b) => {
            const an = parseInt(a.match(/(\d+)/)?.[1] ?? '0', 10);
            const bn = parseInt(b.match(/(\d+)/)?.[1] ?? '0', 10);
            return an - bn;
          });
          const blobs = await Promise.all(
            files.map(async (f) => {
              const name = f.replace(/\.svg$/, '');
              let v = 0;
              try {
                v = Math.floor((await stat(join(dir, f))).mtimeMs / 1000);
              } catch {
                // ignore — use 0
              }
              return { name, v };
            }),
          );
          return { ...source, blobs };
        }),
      );
      res.json({ sources });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to load blobs catalog';
      res.status(500).json({ error: message });
    }
  });

  app.get('/api/elements/blobs/svg/:source/:name', async (req, res) => {
    const { source, name } = req.params;
    if (!/^[a-z0-9-]+$/.test(source) || !/^[a-z0-9-]+$/.test(name)) {
      res.status(400).json({ error: 'Invalid source or blob name' });
      return;
    }
    if (!BLOB_SOURCES.some((s) => s.id === source)) {
      res.status(404).json({ error: 'Unknown blob source' });
      return;
    }
    try {
      const raw = await readFile(join(blobsBaseDir, source, `${name}.svg`), 'utf-8');
      // Blob SVG is served as-is; soft-blur halo headroom is provided by
      // the overlay wrapper itself growing via CSS padding when blur is
      // applied (see overlays.html). That keeps the visible blob the
      // same size as the Size slider regardless of blur amount.
      const svg = raw;
      res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8');
      res.setHeader('Cache-Control', 'public, max-age=3600, must-revalidate');
      res.send(svg);
    } catch {
      res.status(404).json({ error: `Blob "${name}" not found in ${source}` });
    }
  });

  app.get('/api/elements/arrows/svg/:source/:name', async (req, res) => {
    const { source, name } = req.params;
    // Strict allowlist on both segments — keep the read inside data/arrows.
    if (!/^[a-z0-9-]+$/.test(source) || !/^[a-z0-9-]+$/.test(name)) {
      res.status(400).json({ error: 'Invalid source or arrow name' });
      return;
    }
    if (!ARROW_SOURCES.some((s) => s.id === source)) {
      res.status(404).json({ error: 'Unknown arrow source' });
      return;
    }
    try {
      const svg = await readFile(join(arrowsBaseDir, source, `${name}.svg`), 'utf-8');
      res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8');
      // No `immutable` — content can change when scripts re-sync. ETag
      // lets the browser revalidate cheaply.
      res.setHeader('Cache-Control', 'public, max-age=3600, must-revalidate');
      res.send(svg);
    } catch {
      res.status(404).json({ error: `Arrow "${name}" not found in ${source}` });
    }
  });

  app.get('/api/elements/icons/svg/:name', async (req, res) => {
    if (!lucideIconsDir) {
      res.status(500).json({ error: 'lucide-static not installed' });
      return;
    }
    // Only allow lowercase a-z, digits, and hyphens — defends against path
    // traversal since the value flows straight into a filesystem read.
    const name = req.params.name;
    if (!/^[a-z0-9-]+$/.test(name)) {
      res.status(400).json({ error: 'Invalid icon name' });
      return;
    }
    try {
      const svg = await readFile(join(lucideIconsDir, `${name}.svg`), 'utf-8');
      res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8');
      // No `immutable` — content can change when scripts re-sync. ETag
      // lets the browser revalidate cheaply.
      res.setHeader('Cache-Control', 'public, max-age=3600, must-revalidate');
      res.send(svg);
    } catch {
      res.status(404).json({ error: `Icon "${name}" not found` });
    }
  });
}
